version: '3'
services:
  db:
    image: mongo:latest
    volumes:
      - assets:/data/db
    ports:
      - 27017:27017
    networks:
      - spring_demo_net
  web:
    image: getmub/todo:v1
    depends_on:
      - db
    ports:
      - 8090:8080
    links:
      - db 
    networks:
      - spring_demo_net
volumes:
  assets:
networks:
  spring_demo_net:
    driver: overlay
